In [1]:
#3.	Using iris data set, implement naive bayes classification for different
#naive Bayes classification algorithms. 

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('iris.csv')
X = dataset.iloc[:,:4].values
y = dataset['variety'].values
dataset.head(5)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test) 
y_pred
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Accuracy :  0.9333333333333333

   Real Values Predicted Values
0       Setosa           Setosa
1       Setosa           Setosa
2    Virginica       Versicolor
3   Versicolor       Versicolor
4       Setosa           Setosa
5    Virginica        Virginica
6    Virginica        Virginica
7   Versicolor       Versicolor
8   Versicolor       Versicolor
9       Setosa           Setosa
10      Setosa           Setosa
11   Virginica        Virginica
12  Versicolor       Versicolor
13      Setosa           Setosa
14   Virginica        Virginica
15      Setosa           Setosa
16      Setosa           Setosa
17  Versicolor       Versicolor
18  Versicolor        Virginica
19  Versicolor       Versicolor
20      Setosa           Setosa
21  Versicolor       Versicolor
22   Virginica        Virginica
23  Versicolor       Versicolor
24  Versicolor       Versicolor
25  Versicolor       Versicolor
26      Setosa           Setosa
27  Versicolor       Versicolor
28  Versicolor       Versicolor
29  Versicolor       Versicolor

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('iris.csv')
X = dataset.iloc[:,:4].values
y = dataset['variety'].values
dataset.head(5)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test) 
y_pred
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm
# df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
# df

Accuracy :  0.23333333333333334

array([[ 7,  0,  0],
       [13,  0,  0],
       [10,  0,  0]], dtype=int64)

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('iris.csv')
X = dataset.iloc[:,:4].values
y = dataset['variety'].values
dataset.head(5)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test) 
y_pred
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
#cm
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Accuracy :  0.26666666666666666

   Real Values Predicted Values
0       Setosa        Virginica
1    Virginica        Virginica
2       Setosa        Virginica
3    Virginica        Virginica
4    Virginica        Virginica
5       Setosa        Virginica
6       Setosa        Virginica
7    Virginica        Virginica
8   Versicolor        Virginica
9       Setosa        Virginica
10  Versicolor        Virginica
11   Virginica        Virginica
12  Versicolor        Virginica
13      Setosa        Virginica
14  Versicolor        Virginica
15      Setosa        Virginica
16  Versicolor        Virginica
17  Versicolor        Virginica
18   Virginica        Virginica
19  Versicolor        Virginica
20      Setosa        Virginica
21      Setosa        Virginica
22  Versicolor        Virginica
23      Setosa        Virginica
24      Setosa        Virginica
25  Versicolor        Virginica
26   Virginica        Virginica
27   Virginica        Virginica
28  Versicolor        Virginica
29      Setosa        Virginica